name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Setup deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Check and test
        run: make check ci

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: cov_profile.lcov